import React from 'react';
import {
  PanelLeft,
  ArrowLeft,
  ArrowRight,
  RotateCw,
  Lock,
  Copy,
  PanelRight,
  ChevronsLeft,
  Search,
  LayoutDashboard,
  Package,
  Truck,
  Warehouse,
  MessageSquare,
  Map,
  Wallet,
  TrendingUp,
  FileBarChart,
  Users,
  ShoppingCart,
  Shield,
  LifeBuoy,
  MessageCircle,
  Settings,
  Zap,
  ChevronRight,
  ChevronDown,
  Menu,
  Share2,
  Bell,
  UserPlus,
  LayoutGrid,
  Table,
  Filter,
  ArrowUpDown,
  SlidersHorizontal,
  Upload,
  Plus,
  Info,
  ArrowUp,
  ArrowDown,
  Thermometer,
  MapPinOff,
  Timer,
  PackageX,
  Star,
  Code,
  Pencil,
  Trash2,
  MoreHorizontal,
  X,
  ChevronLeft,
  Siren,
  AlertTriangle,
  Check,
  Clock,
  Play,
  Activity,
  Globe,
  MapPin
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<any>> = {
  'panel-left': PanelLeft,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'rotate-cw': RotateCw,
  'lock': Lock,
  'copy': Copy,
  'panel-right': PanelRight,
  'chevrons-left': ChevronsLeft,
  'search': Search,
  'layout-dashboard': LayoutDashboard,
  'package': Package,
  'truck': Truck,
  'warehouse': Warehouse,
  'message-square': MessageSquare,
  'map': Map,
  'wallet': Wallet,
  'trending-up': TrendingUp,
  'file-bar-chart': FileBarChart,
  'users': Users,
  'shopping-cart': ShoppingCart,
  'shield': Shield,
  'life-buoy': LifeBuoy,
  'message-circle': MessageCircle,
  'settings': Settings,
  'zap': Zap,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'menu': Menu,
  'share-2': Share2,
  'bell': Bell,
  'user-plus': UserPlus,
  'layout-grid': LayoutGrid,
  'table': Table,
  'filter': Filter,
  'arrow-up-down': ArrowUpDown,
  'sliders-horizontal': SlidersHorizontal,
  'upload': Upload,
  'plus': Plus,
  'info': Info,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'thermometer': Thermometer,
  'map-pin-off': MapPinOff,
  'timer': Timer,
  'package-x': PackageX,
  'star': Star,
  'code': Code,
  'pencil': Pencil,
  'trash-2': Trash2,
  'more-horizontal': MoreHorizontal,
  'x': X,
  'chevron-left': ChevronLeft,
  'siren': Siren,
  'triangle-alert': AlertTriangle,
  'alert-triangle': AlertTriangle,
  'check': Check,
  'clock': Clock,
  'play': Play,
  'activity': Activity,
  'globe': Globe,
  'map-pin': MapPin
};

interface IconProps {
  name: string;
  size?: number | string;
  className?: string;
  width?: number | string;
  height?: number | string;
  strokeWidth?: number;
}

export default function Icon({ name, size, className, width, height, ...props }: IconProps) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) {
    // Return a fallback question mark or nothing
    return null;
  }
  return <LucideIcon size={size} className={className} width={width} height={height} {...props} />;
}
